# Generated by Django 2.2.5 on 2020-02-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_coverphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolioPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolioPhoto_name', models.CharField(max_length=50)),
                ('portfolioPhoto_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
