# Generated by Django 2.2.5 on 2020-02-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_portfoliophoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliophoto',
            name='portfolioPhoto_caption',
            field=models.CharField(default='caption', max_length=100),
        ),
        migrations.AddField(
            model_name='portfoliophoto',
            name='portfolioPhoto_heading',
            field=models.CharField(default='label', max_length=50),
        ),
    ]
