# Generated by Django 2.2.5 on 2020-04-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200215_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_name', models.CharField(max_length=50)),
                ('services_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Add',
        ),
    ]
