# Generated by Django 3.0.2 on 2020-04-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200331_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolioPhoto_hairdo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolioPhoto_hairdo_name', models.CharField(max_length=50)),
                ('portfolioPhoto_hairdo_image', models.ImageField(upload_to='images/hairdo/')),
                ('portfolioPhoto_hairdo_heading', models.CharField(default='label', max_length=50)),
                ('portfolioPhoto_hairdo_caption', models.CharField(default='caption', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='portfolioPhoto_henna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolioPhoto_henna_name', models.CharField(max_length=50)),
                ('portfolioPhoto_henna_image', models.ImageField(upload_to='images/henna/')),
                ('portfolioPhoto_henna_heading', models.CharField(default='label', max_length=50)),
                ('portfolioPhoto_henna_caption', models.CharField(default='caption', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='portfolioPhoto_makeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolioPhoto_makeup_name', models.CharField(max_length=50)),
                ('portfolioPhoto_makeup_image', models.ImageField(upload_to='images/makeup/')),
                ('portfolioPhoto_makeup_heading', models.CharField(default='label', max_length=50)),
                ('portfolioPhoto_makeup_caption', models.CharField(default='caption', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='portfolioPhoto',
        ),
    ]
