# Generated by Django 3.0.2 on 2020-05-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200414_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='html_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_1', models.CharField(max_length=50)),
                ('value_2', models.CharField(max_length=100)),
            ],
        ),
    ]
