# Generated by Django 3.0.2 on 2020-07-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200728_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliophoto_makeup',
            name='portfolioPhoto_makeup_column',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
    ]
