# Generated by Django 3.0.2 on 2020-07-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200728_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliophoto_makeup',
            name='portfolioPhoto_makeup_column',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default='1', max_length=1),
        ),
    ]
